name: "OSSF Scorecard"
on:
  push:
  pull_request:
jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Scorecard
        uses: ossf/scorecard-action@v1
        with:
          results-file: results.sarif
